### PR TITLE
Revert "HACK: scripts: wireguard: Force download from master"

### PR DESCRIPTION
**Pull request by zx2c4**
This is very bad and needs to be reverted.

### CODE REVIEW

**Comment by xdevs23** [comment]
No worries, I'll merge upstream anyway, so this will be fixed by that. Thanks for reaching out, though.

**Comment by zx2c4** [comment]
Upstream? As in kernel.org or...?

**Comment by xdevs23** [comment]
https://github.com/nathanchance/op5 branch 8.1.0-unified

**Comment by zx2c4** [comment]
I see. Please do let me know when you do that. This is quite important.

**Comment by xdevs23** [comment]
Expect it to be in a few hours if not less.

**Comment by xdevs23** [comment]
Here you go: https://github.com/halogenOS/android_kernel_oneplus_msm8998/commit/0fd3dd597fa8d211fcb3bb191bcccf172b67181d

Just merged it.

**Comment by zx2c4** [comment]
Thanks.

**Comment by xdevs23** [comment]
No problem. Thank you for contributing.

**Pull request closed without merging**
